siteGuid: em3n8gy
sourceDirectory: /Users/gmccreight/gmcc/inhalt
initialSitePageTitle: considering dark software factories
initialSitePageDirectory: sonst
defaultTraversalSitePageTitle: considering dark software factories
defaultTraversalSitePageDirectory: sonst
generatedSiteVersions:
  - vkEZh5j
archivedAt: null
siteCreatedAt: 2026-06-06T22:17:46.271Z
siteUpdatedAt: 2026-06-06T22:17:46.271Z
siteLastPublishedAt: null
siteNotes: ""
